build: off

environment:
  # install as much as we can from main anaconda
  # channel, and use conda-forge as a fallback
  ANACONDA_DEPS:    pytest pytest-cov coverage cython numpy zlib six
  CONDA_FORGE_DEPS: pydicom nibabel
  matrix:
    - PYTHON_VERSION:   "2.7"
      PYTHON:           "C:\\Miniconda"
      MINICONDA:        "C:\\Miniconda"
      PYTHON_ARCH:      "32"
      CONDA_FORGE_DEPS: "nibabel pydicom=1.4"

    - PYTHON_VERSION:   "2.7"
      PYTHON:           "C:\\Miniconda-x64"
      MINICONDA:        "C:\\Miniconda-x64"
      PYTHON_ARCH:      "64"
      CONDA_FORGE_DEPS: "nibabel pydicom=1.4"

    - PYTHON_VERSION: "3.6"
      PYTHON:         "C:\\Miniconda36"
      MINICONDA:      "C:\\Miniconda36"
      PYTHON_ARCH:    "32"

    - PYTHON_VERSION: "3.6"
      PYTHON:         "C:\\Miniconda36-x64"
      MINICONDA:      "C:\\Miniconda36-x64"
      PYTHON_ARCH:    "64"

    - PYTHON_VERSION: "3.7"
      PYTHON:         "C:\\Miniconda37"
      MINICONDA:      "C:\\Miniconda37"
      PYTHON_ARCH:    "32"

    - PYTHON_VERSION: "3.7"
      PYTHON:         "C:\\Miniconda37-x64"
      MINICONDA:      "C:\\Miniconda37-x64"
      PYTHON_ARCH:    "64"

    - PYTHON_VERSION: "3.8"
      PYTHON:         "C:\\Miniconda37"
      MINICONDA:      "C:\\Miniconda37"
      PYTHON_ARCH:    "32"

    - PYTHON_VERSION: "3.8"
      PYTHON:         "C:\\Miniconda37-x64"
      MINICONDA:      "C:\\Miniconda37-x64"
      PYTHON_ARCH:    "64"

# cython not currently available
#    - PYTHON_VERSION: "3.9"
#      PYTHON:         "C:\\Miniconda37"
#      MINICONDA:      "C:\\Miniconda37"
#      PYTHON_ARCH:    "32"
#
#    - PYTHON_VERSION: "3.9"
#      PYTHON:         "C:\\Miniconda37-x64"
#      MINICONDA:      "C:\\Miniconda37-x64"
#      PYTHON_ARCH:    "64"


install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda update  --yes -q conda
  - conda create  --yes -n test_env python=%PYTHON_VERSION%
  - activate test_env
  - conda install --yes                %ANACONDA_DEPS%
  - conda install --yes -c conda-forge %CONDA_FORGE_DEPS%
  - set ZLIB_HOME=%CONDA_PREFIX%\\Library
  - python setup.py develop


# Run slow tests only on master branch.
# Tests marked with zran_test can only
# be run on POSIX systems.
for:
-
  branches:
    only:
      - master
  environment:
    matrix:
      - TEST_ARGS: "-m \"not zran_test\""
      - TEST_ARGS: "-m \"not zran_test\" --concat"
-
  branches:
    except:
      - master
  environment:
    TEST_ARGS: "-m \"not (zran_test or slow_test)\""

test_script:
  - pytest -v -s %TEST_ARGS%
